baseurl = "http://shanemook.com/"

title = "shanemook.com"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-76548214-1"
publishdir = "dist"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Shane Mook - Full Stack Developer - Resume"
    author = "Shane Mook"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Shane Mook"
        tagline = "Full Stack Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//shanemook.com"
        title = "shanemook.com"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: shane.mook@gmail.com"
        title = "shane.mook@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+3125020353"
        title = "312-502-0353"

        [[params.contact.list]]
        class = "website"
        icon = "fa-google-plus"
        url = "//plus.google.com/+ShaneMook"
        title = "+ShaneMook"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/shane-mook"
        title = "shane-mook"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/smook1980"
        title = "smook1980"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/smook1980"
        title = "@smook1980"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Computer Science"
        college = "University of Wisconsin - La Crosse"
        dates = ""

    # Languages section
    [params.languages]
        enable = false
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

        [[params.languages.list]]
        language = "French"
        level = "Professional"

        [[params.languages.list]]
        language = "Russian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Tucker - The Best Dog, Ever"

        [[params.interests.list]]
        interest = "Travel"

        [[params.interests.list]]
        interest = "Backpacking and Hiking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Full stack software engineer with over six and a half years of experience working in an agile team environment to produce web and mobile applications. An advocate for test driven design, refactoring code when appropriate to keep code aligned with a changing business domain, and high code standards to maintain team velocity as a project matures. Experienced maintaining and scaling complicated back-end systems using current dev-ops best practices to meet increasing and changing business demands. In addition to my primary role as a software engineer I have acted in several other roles to adapt to business needs -- server administration, quality assurance, test engineer, database administrator, project manager and technical team lead."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Freelance Consultant"
        dates = "March 2016 - Present"
        company = "Chicago, IL"
        details = "Worked remotely with several small bay area agile teams with Ruby, Ruby on Rails, Backbone, React, VueJS, ES2015, CoffeeScript, Webpack, Babel and Javascript technologies. Projects were deployed to Heroku and AWS. Practiced test-driven development with scrum and kanban project planning."

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "May 2009 - March 2016"
        company = "NCSA Athletic Recruit, Chicago, IL"
        details = "Over five years experience as a software developer in an agile environment. Worked with Ruby on Rails, RSpec, Grape, Sinatra, Java, JUnit, Spring, Struts, Hibernate, and Objective-C/iOS to create web and mobile applications. Created fluid single page interfaces with Javascript, CoffeeScript, BackboneJS, and SASS/CSS. Partnered with product owners to maximize business value with a minimal investment in development time. All production code was written in a test-driven manner, often while pair programming. Applied dev-ops techniques to manage an increasingly complex infrastructure using chef in a test-driven configuration with ChefSpec and Vagrant. Supported close to forty production servers in a highly available clustered configuration utilizing HAProxy, Apache HTTP, Puma, Passenger, Tomcat, MySQL, MS SQL Server, MySQL, Postgres, ElasticSearch, Beanstalk, Drupal and Wordpress. Projects deployed to Amazon AWS, RackSpace and a private VMWare cluster. Worked to eliminate single points of failure, reduce downtimes, and scale as demand increased."

        [[params.jobs.list]]
        position = "Network and Support Specialist"
        dates = "May 2008 - May 2009"
        company = "NCSA Athletic Recruit, Chicago, IL"
        details = "Involved in network operations and server administration working with Linux, Windows Server, Active Directory, Apache HTTPD, CVS, Python, HTML/Javascript, custom SQL reports."

        [[params.jobs.list]]
        position = "Assistant Manager of Technology"
        dates = "March 2002 - May 2008"
        company = "FedEx Office, Madison, WI & Skokie, IL"
        details = "Provided field technology support for FedEx Office locations."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Ruby"
        level = "98%"

        [[params.skills.list]]
        skill = "RSpec"
        level = "98%"

        [[params.skills.list]]
        skill = "Ruby On Rails"
        level = "98%"

        [[params.skills.list]]
        skill = "ES2015 / Javascript / Coffescript"
        level = "95%"

        [[params.skills.list]]
        skill = "Linux - Administration / Shell Scripting"
        level = "95%"

        [[params.skills.list]]
        skill = "Java - JUnit, Spring, Struts, Hybernate"
        level = "90%"

        [[params.skills.list]]
        skill = "PostgresSQL, MySQL, MS Sql Server"
        level = "90%"

        [[params.skills.list]]
        skill = "Semantic HTML5 & CSS"
        level = "85%"

        [[params.skills.list]]
        skill = "Go"
        level = "75%"

        [[params.skills.list]]
        skill = "Webpack"
        level = "80%"

        [[params.skills.list]]
        skill = "SASS/LESS"
        level = "75%"

        [[params.skills.list]]
        skill = "Amazon Web Services"
        level = "70%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Shane Mook"
