baseurl = "http://shanemook.com/"
title = "shanemook.com"
languageCode = "en-us"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishdir = "dist"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Shane Mook - Full Stack Developer - Resume"
    author = "Shane Mook"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Shane Mook"
        tagline = "Full Stack Developer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//shanemook.com"
        title = "shanemook.com"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: shane.mook@gmail.com"
        title = "shane.mook@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+3125020353"
        title = "312-502-0353"

        [[params.contact.list]]
        class = "website"
        icon = "fa-google-plus"
        url = "//plus.google.com/+ShaneMook"
        title = "+ShaneMook"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/shane-mook"
        title = "shane-mook"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/smook1980"
        title = "smook1980"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/smook1980"
        title = "@smook1980"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Computer Science"
        college = "University of Wisconsin - La Crosse"
        dates = "2008 - 2009"

    # Languages section
    [params.languages]
        enable = false
        title = "Languages"

        [[params.languages.list]]
        language = "English"
        level = "Native"

        [[params.languages.list]]
        language = "French"
        level = "Professional"

        [[params.languages.list]]
        language = "Russian"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "My Dog - Tucker"

        [[params.interests.list]]
        interest = "Backpacking and Hiking"

        [[params.interests.list]]
        interest = "Travel"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "Full stack software engineer with over six and half years of expierence working in a team environment to produce outstanding web and mobile applications. An advocate for test drive design, refactoring code when appropriate to stay in line with the change business doamin, and high code stadards to maintain team velocity. Expeirence maintaining and scaling complicated backend systems use devops best practices to meet increasing and changing business demands. In addition to my primary role as a software engineer I have acted in several other roles to adapt to business needs -- server adminstrator, quality assurance, test engineer, database administrator, project manager and technical team lead."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Freelance Consultant"
        dates = "March 2016 - Present"
        company = "Shane Mook Consulting, Chicago"
        details = "TBD"

        [[params.jobs.list]]
        position = "Senior Software Engineer"
        dates = "May 2009 - March 2016"
        company = "NCSA Athletic Recruit, Chicago"
        details = "Full stack software developer with over five years experience in an agile environment.   I've worked extensively with Java, Spring, Struts, Hibernate, Ruby on Rails, Sintra to create tradiiontal web applications and restful APIs for client consumption.  Created fluid single page interfaces with Javascript, CoffeeScript, BackboneJS, EmberJS, and SASS/CSS.  Work closely with product owners to produce business value.  All production code is written in a test drive manner, often while pair programming.  Applied devops techniques to manage an increasingly complex infrastructure using chef in a test drive configuration with chefspec and vagrant.  Support close to 40 production servers in a highly available clustered configuration utilizing HAProxy, Apache HTTPD, Puma, Passenger, Tomcat, MySQL, MS SQL Server, MySQL, Postgres, ElasticSearch, Beanstalk, Drupal and Wordpress.  Servers are deployed to Amazon AWS, RackSpace and a private VMWare cluster.  Worked to eliminate single points of failure to reduce downtimes.  Recent work has been focussed on iOS and Android development."

        [[params.jobs.list]]
        position = "Network and Support Specialist"
        dates = "May 2008 - May 2009"
        company = "NCSA Athletic Recruit, Chicago"
        details = "Windows Client and Server Administration, Active Directory, Group Policy, Linux LAMP Administration, CVS Repository Administration, IP Phone Administration, Active Directory Integration With Various Systems, Python Scripting, HTML / JavaScript, Sonicwall Administration."

        [[params.jobs.list]]
        position = "Assistant Manager of Technology"
        dates = "March 2002 - May 2008"
        company = "FedEx Office, Madison, WI & Skokie, IL"
        details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Ruby"
        level = "98%"

        [[params.skills.list]]
        skill = "Ruby On Rails"
        level = "98%"

        [[params.skills.list]]
        skill = "Javascript/Coffescript"
        level = "95%"

        [[params.skills.list]]
        skill = "Java - Spring, Hybernate"
        level = "90%"

        [[params.skills.list]]
        skill = "Semantic HTML5 & CSS"
        level = "85%"

        [[params.skills.list]]
        skill = "Devops - Docker, Linux, Postgres DBA"
        level = "80%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = "Shane Mook"